### ISSUE TITLE
Error when java jar in Linux ClassNotFoundException

### ISSUE THREAD

**Issue by Vanessamae23** [nus-cs2103-AY2324S1/forum#140]
Hi i keep on getting this error in Linux but i m running fine when in windows for the Jar file

```
java.lang.ClassNotFoundException: com.sun.glass.ui.gtk.GtkPlatformFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:42)
        at com.sun.glass.ui.Application.run(Application.java:144)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:829)
Failed to load Glass factory class
Exception in thread "main" java.lang.NullPointerException
        at com.sun.glass.ui.Application.run(Application.java:144)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Any help is appreciated thank you

**Comment by LicongHuang** [comment]
Hello, could you share the configurations for which was used to generate the jar file? For example, the `gradle.build` if you used Gradle to generate the jar file. Also, what have you tried to resolve this issue? Thanks.

**Comment by Vanessamae23** [comment]
I have tried in my friend's windows laptop and it worked but not in linux OS, i have nt tried in MacOS tho
```
plugins {
    id 'checkstyle'
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'org.openjfx.javafxplugin' version '0.0.13'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'

}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

javafx {
    version = '17'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
application {
    mainClass.set("seedu.Launcher")
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}

checkstyle {
    toolVersion = '10.2'
}

run {
    standardInput = System.in
}

```

**Comment by damithc** [comment]
@Vanessamae23 Check if the [AB3 Jar file](https://github.com/se-edu/addressbook-level3/releases) works in the same Linux machine that you encountered the above issue.

**Comment by SynapseProgramming** [comment]
Hihi, i think a while back, I tried to help one of my friends  test his ip. (I was running Ubuntu 22.04 LTS on my desktop) and I could not get it to fully work(it still kinda ran). Maybe you could try to install a different jdk version on your linux machine ?

**Comment by Vanessamae23** [comment]
> @Vanessamae23 Check if the [AB3 Jar file](https://github.com/se-edu/addressbook-level3/releases) works in the same Linux machine that you encountered the above issue.

Yes this worked though and i think my friend's (but didnt use intellij) also worked on my linux

**Comment by damithc** [comment]
@Vanessamae23 to confirm, you generated the jar file using `./gradlew clean shadowjar` command? If not, you can try that too.

**Comment by Vanessamae23** [comment]
yep,

**Comment by Vanessamae23** [comment]
seems to work on some MacOS and not work on some MacOS

**Comment by damithc** [comment]
@Vanessamae23 you can share the said jar file here so that others can try it out as well.

**Comment by Vanessamae23** [comment]
[duke.zip](https://github.com/nus-cs2103-AY2324S1/forum/files/12639712/duke.zip)

Here is my jar file, would be grateful if anyone can help,. Thank u in advance

**Comment by cheeheng** [comment]
Hi @Vanessamae23, I am from a previous batch. I got this error while trying to run the duke.jar file in Ubuntu 23.04. I am using openjdk 11.0.20.1.

```
Sep 16, 2023 12:09:25 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1ee178c8'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:276)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

On the other hand, AB3 jar file runs fine. 

Perhaps you could try [this fix](https://github.com/nus-cs2103-AY2223S1/forum/issues/213) from a previous semester. You seem to have a javafx block in the build.gradle file, perhaps you can try removing it.

**Comment by Vanessamae23** [comment]
@cheeheng Okay thank you, it solved the problem 
This is the fix for my problem in case anyone encounters the same thing for cross platform issues
>> I also get the same error in Linux (Arch). For fixing the issue: remove the javafx {} block at the end of build.gradle. That part is actually restricting the packages.
