### ISSUE TITLE
Facing internal exceptions in JavaFX when launching application

### ISSUE THREAD

**Issue by applepiofmyeye** [nus-cs2103-AY2324S1/forum#163]
Development environment:
- IntelliJ IDEA 2022.3.1
- macOS Ventura 13.4.1
- Java version 11
- Project SDK: zulu-11
- JavaFX 17.0.7

In debug mode, I am able to step through the internal exceptions, then run the application after stepping over these, as seen below. 

<img width="1440" alt="Screenshot 2023-09-20 at 6 31 06 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122950712/b357a398-a4bc-4dac-9ee4-cd656fdf33f7">
<img width="1440" alt="Screenshot 2023-09-20 at 6 36 27 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122950712/590c464e-d024-4af7-949a-9e14bb9b1821">

When I launch the app by **running** the Launcher.java file, however, I face the following messages:
```
6:37:40 pm: Executing ':Launcher.main()'...

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE

> Task :Launcher.main()
2023-09-20 18:37:42.069 java[40743:14686953] XType: Using static font registry.
Sep 20, 2023 6:37:47 PM com.sun.glass.ui.mac.MacApplication lambda$waitForReactivation$6
WARNING: Timeout while waiting for app reactivation
RenderJob.run: internal exception
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4351)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1310)
	at javafx.graphics/com.sun.glass.ui.Screen.getMainScreen(Screen.java:59)
	at javafx.graphics/com.sun.prism.es2.ES2Pipeline.getScreenForAdapter(ES2Pipeline.java:150)
	at javafx.graphics/com.sun.prism.es2.ES2Pipeline.findDefaultResourceFactory(ES2Pipeline.java:161)
	at javafx.graphics/com.sun.prism.es2.ES2Pipeline.getDefaultResourceFactory(ES2Pipeline.java:182)
	at javafx.graphics/com.sun.prism.GraphicsPipeline.getDefaultResourceFactory(GraphicsPipeline.java:151)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.lambda$createResourceFactory$2(QuantumRenderer.java:163)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

From the debugger, the line in my code that triggers this is my Main::start method:
<img width="677" alt="Screenshot 2023-09-20 at 6 33 16 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122950712/55ac136b-c44f-4bfd-ab46-b82d7f1a863c">

```java
    @Override
    public void start(Stage stage) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(Main.class.getResource("/view/MainWindow.fxml"));
            AnchorPane ap = fxmlLoader.load(); // This line
            Scene scene = new Scene(ap);
            stage.setScene(scene);
            fxmlLoader.<MainWindow>getController().setBarbie(barbie);
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

This hasn't happened before, and I have tried with my previous iterations (branch-Level-10, branch-A-CodeQuality) and I still get the same message. Would really appreciate any form of help, thank you!

**Comment by damithc** [comment]
@applepiofmyeye I recommend that you push the code to a branch in your fork and share the branch name here so that other can try to replicate the exact problem (or do a more thorough examination of the code).

**Comment by applepiofmyeye** [comment]
The branch "branch-A-Assertions" doesn't seem to have this issue, though the branch "branch-BCD-Extension" does

**Comment by damithc** [comment]
While waiting for inputs from others, here are some things you can try:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by applepiofmyeye** [comment]
Thanks prof! It suddenly started working again.. I've pushed my latest commit in the branch "branch-BCD-Extension", which ended up fixing all my previous iterations as well..? (Even though I did not change their code) I'm still not really sure why
