### ISSUE TITLE
Unable to obtain a workable `jar` file with intellij

### ISSUE THREAD

**Issue by XihuaZ** [nus-cs2103-AY2324S1/forum#198]
I am unsure why, but when I try to build the `shadowJar`, I am unable to obtain a functional `jar` file.

However, for reason unknown, using `./gradlew shadowJar` results in a functional `jar` file. 

Anyone knows why Intellij can't build a functional `jar` file? If `./gradlew shadowJar` functions well, can I just ignore the fact that my Intellij can't build a functional `jar` file?

Error message from Intellij's `jar` file:

```
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @67b7880c'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/xihua/.openjfx/cache/17.0.7/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/xihua/.openjfx/cache/17.0.7/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1850)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:829)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/xihua/.openjfx/cache/17.0.7/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/xihua/.openjfx/cache/17.0.7/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1850)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:43)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:829)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

Meanwhile, with `./gradlew shadowJar` it is compilable.

```
Sep 23, 2023 11:02:58 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 20.0.1 by JavaFX runtime of version 19.0.4
Sep 23, 2023 11:02:58 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 20.0.1 by JavaFX runtime of version 19.0.4
```

**Comment by woojiahao** [comment]
Think there's some missing context, like what is "building the `shadowJar`? Are you referring to using Intellij's built-in JARing? If so, then it's not working because it does not build a fat JAR that contains all the dependencies like JavaFX and JUnit. ShadowJAR resolves this by handling it for you when you run `./gradlew shadowJar`.

You might want to read up more about what fat JARs are and the types of JARs you can get:
- https://www.geeksforgeeks.org/jar-files-java/
- https://stackoverflow.com/questions/19150811/what-is-a-fat-jar
- https://imperceptiblethoughts.com/shadow/introduction/

Further clarification: Intellij's built-in JARing functionality is not the same as ShadowJAR, so using Intellij's JARing does not immediately guarantee that you are building a fat JAR

**Comment by XihuaZ** [comment]
I run this on the Intellij version though. I thought this would be the shadowJar equivalent to `./gradlew shadowJar`?
<img width="273" alt="Screenshot 2023-09-23 at 11 04 27 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/91673283/60e68e85-df8e-4416-8a6b-8605b829815b">

**Comment by woojiahao** [comment]
Ah, then it is. Where are you retrieving the JAR file from? `build/libs`?

**Comment by XihuaZ** [comment]
yes. but i am not sure why, intellij shadowJar builds 2 jar file. 1 bot.jar (the one I want) and 1 ip.jar (which I am unsure why). However, `gradlew` doesn't generate 2 jar files though...

**Comment by damithc** [comment]
@XihuaZ you can remove the following line in your build.gradle to prevent shadowjar creating two jar files.

`dependsOn("distZip", "distTar")`
