### ISSUE TITLE
Jar created using Gradle fails

### ISSUE THREAD

**Issue by mamayuan** [nus-cs2103-AY2324S1/forum#201]
My build.gradle looks no different than other people's. 

But when I try java -jar DaDaYuan.jar on terminal, I get the following issue:
java.lang.ClassNotFoundException: duke.Launcher

I have tried to debug using: jar tf DaDaYuan.jar
It seems that it does not contain the class files my project created, what am I supposed to do? Please send help.

**Comment by vivienherq** [comment]
i think you might need to set:
```
application {
    mainClass.set("duke.ui.Launcher")
}
```
instead of 
```
application {
    mainClass.set("duke.Launcher")
}
```
since your Launcher is in the duke.ui package
hope this helps!

**Comment by mamayuan** [comment]
Thx, I have tried that and it worked, but i run into another issue:
Sep 24, 2023 3:30:00 PM com.sun.javafx.application.PlatformImpl startup                    
Warning: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5c030d96'
javafx.fxml.LoadException:                                                        
file:/C:/Users/94866/Documents/ip/build/libs/DaDaYuan.jar!/view/MainWindow.fxml:14

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2714)                    
        at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:944)              
        at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:981)
        at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:230)                
        at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:755)           
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2845)                       
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2641)                                  
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2555)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2523)
        at duke.ui.Main.initializeMainWindow(Main.java:48)
        at duke.ui.Main.start(Main.java:34)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:939)
        ... 18 more
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at duke.ui.MainWindow.loadImage(MainWindow.java:94)
        at duke.ui.MainWindow.<init>(MainWindow.java:30)
        ... 23 more
What is going on...

**Comment by AlagappanRa** [comment]
Could you share the build gradle file you are using. The issue you are facing maybe similar to #159.

**Comment by mamayuan** [comment]
I just followed what was taught... here is the file content
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

checkstyle {
    toolVersion = '10.2'
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("duke.ui.Launcher")
}

shadowJar {
    archiveBaseName = "DaDaYuan"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}

run{
    standardInput = System.in
}

**Comment by damithc** [comment]
@mamayuan You may want to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

**Comment by mamayuan** [comment]
```
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

checkstyle {
    toolVersion = '10.2'
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("duke.ui.Launcher")
}

shadowJar {
    archiveBaseName = "DaDaYuan"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}

run{
    standardInput = System.in
}
```

**Comment by damithc** [comment]
@mamayuan If you haven't done so, push your latest code to your fork so that others can try to reproduce the problem using your exact code.

**Comment by mamayuan** [comment]
Just did that, thank you prof. Btw, I am working on Windows, if that matters in the creation of Jar...

**Comment by AlagappanRa** [comment]
Looking closer at the stacktrace dump, 
```java
    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2714)                    
    at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:944)              
    at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:981)
    at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:230)                
    at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:755)           
    at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2845)                       
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2641)                                  
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2555)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2523)
    at duke.ui.Main.initializeMainWindow(Main.java:48)
    at duke.ui.Main.start(Main.java:34)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:939)
```
This first part can be ignored as it is a warning - usually, right before the warning there should be a message asking you to "ignore the JavaFx message". 


```java
Caused by: java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:221)
at duke.ui.MainWindow.loadImage(MainWindow.java:94)
at duke.ui.MainWindow.(MainWindow.java:30)
... 23 more
```

This is more concerning, you should probably check your `MainWindow.java - line 30` to see where the null pointer exception is being raised.  Likely due to you calling/referencing the attribute of an uninitialized variable.

**Comment by mamayuan** [comment]
Right! The path name I provided was incorrect, now it has been solved. Thank you very much!
