### ISSUE TITLE
UnsatisfiedLinkError when running JAR File on Mac

### ISSUE THREAD

**Issue by dinde2004** [nus-cs2103-AY2324S1/forum#215]
Can someone help me resolve this error when I am trying to run my JAR File on Mac?

Context:
* OS where the JAR File generated: Windows
* Testing: The JAR File ran well on Windows (both in my and my friend's laptops), but not on Mac
* Java Version: 11

`build.gradle`:
```
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("duke.Launcher")
}

shadowJar {
    archiveFileName = "duke.jar"
    archiveBaseName = "duke"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}

run {
    standardInput = System.in
}

```

Error:
```
com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @57066d88'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/hohong/.openjfx/cache/17.0.7/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/hohong/.openjfx/cache/17.0.7/libprism_es2.dylib
 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2622)
 at java.base/java.lang.Runtime.load0(Runtime.java:765)
 at java.base/java.lang.System.load(System.java:1835)
 at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource([NativeLibLoader.java:217](https://nativelibloader.java:217/))
 at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource([NativeLibLoader.java:197](https://nativelibloader.java:197/))
 at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal([NativeLibLoader.java:138](https://nativelibloader.java:138/))
 at com.sun.glass.utils.NativeLibLoader.loadLibrary([NativeLibLoader.java:54](https://nativelibloader.java:54/))
 at com.sun.prism.es2.ES2Pipeline.lambda$static$0([ES2Pipeline.java:63](https://es2pipeline.java:63/))
 at java.base/java.security.AccessController.doPrivileged(Native Method)
 at com.sun.prism.es2.ES2Pipeline.<clinit>([ES2Pipeline.java:52](https://es2pipeline.java:52/))
 at java.base/java.lang.Class.forName0(Native Method)
 at java.base/java.lang.Class.forName(Class.java:315)
 at com.sun.prism.GraphicsPipeline.createPipeline([GraphicsPipeline.java:218](https://graphicspipeline.java:218/))
 at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init([QuantumRenderer.java:92](https://quantumrenderer.java:92/))
 at com.sun.javafx.tk.quantum.QuantumRenderer$[PipelineRunnable.run](https://pipelinerunnable.run/)([QuantumRenderer.java:125](https://quantumrenderer.java:125/))
 at java.base/java.lang.Thread.run(Thread.java:834)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/hohong/.openjfx/cache/17.0.7/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/hohong/.openjfx/cache/17.0.7/libprism_sw.dylib
 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2622)
 at java.base/java.lang.Runtime.load0(Runtime.java:765)
 at java.base/java.lang.System.load(System.java:1835)
 at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource([NativeLibLoader.java:217](https://nativelibloader.java:217/))
 at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource([NativeLibLoader.java:197](https://nativelibloader.java:197/))
 at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal([NativeLibLoader.java:138](https://nativelibloader.java:138/))
 at com.sun.glass.utils.NativeLibLoader.loadLibrary([NativeLibLoader.java:54](https://nativelibloader.java:54/))
 at com.sun.prism.sw.SWPipeline.lambda$static$0([SWPipeline.java:43](https://swpipeline.java:43/))
 at java.base/java.security.AccessController.doPrivileged(Native Method)
 at com.sun.prism.sw.SWPipeline.<clinit>([SWPipeline.java:42](https://swpipeline.java:42/))
 at java.base/java.lang.Class.forName0(Native Method)
 at java.base/java.lang.Class.forName(Class.java:315)
 at com.sun.prism.GraphicsPipeline.createPipeline([GraphicsPipeline.java:218](https://graphicspipeline.java:218/))
 at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init([QuantumRenderer.java:92](https://quantumrenderer.java:92/))
 at com.sun.javafx.tk.quantum.QuantumRenderer$[PipelineRunnable.run](https://pipelinerunnable.run/)([QuantumRenderer.java:125](https://quantumrenderer.java:125/))
 at java.base/java.lang.Thread.run(Thread.java:834)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
 at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance([QuantumRenderer.java:283](https://quantumrenderer.java:283/))
 at com.sun.javafx.tk.quantum.QuantumToolkit.init([QuantumToolkit.java:254](https://quantumtoolkit.java:254/))
 at com.sun.javafx.tk.Toolkit.getToolkit([Toolkit.java:266](https://toolkit.java:266/))
 at com.sun.javafx.application.PlatformImpl.startup([PlatformImpl.java:291](https://platformimpl.java:291/))
 at com.sun.javafx.application.PlatformImpl.startup([PlatformImpl.java:163](https://platformimpl.java:163/))
 at com.sun.javafx.application.LauncherImpl.startToolkit([LauncherImpl.java:659](https://launcherimpl.java:659/))
 at com.sun.javafx.application.LauncherImpl.launchApplication1([LauncherImpl.java:679](https://launcherimpl.java:679/))
 at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2([LauncherImpl.java:196](https://launcherimpl.java:196/))
 at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
 at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRende
```

[Link to JAR File](https://github.com/dinde2004/ip/releases/tag/A-Release)
Thank you and have a nice day!

**Comment by damithc** [comment]
@dinde2004 Also ask your friend to run the `java -version` command to see if s/he is using the exact JDK version we have prescribed for Mac users (i.e., the Zulu distribution with JavaFX).

**Comment by sp4ce-cowboy** [comment]
@dinde2004 I'm using OpenJDK 11.0.19 on macOS Ventura 13.5 and it works on my mac.

<img width="742" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/19762596/57150c25-40d3-4e25-99f3-47a920a67353">

<img width="512" alt="Screenshot 2023-09-27 at 5 35 19 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/19762596/e64f4bc9-d652-45e3-98fa-6f9b45d50258">

**Comment by dinde2004** [comment]
Thank you @sp4ce-cowboy for helping me test my JAR file on Mac! I will close this issue now
