### ISSUE TITLE
Cant run Tp main file, Quantum Renderer : no suitable pipeline

### ISSUE THREAD

**Issue by Nid21cs** [nus-cs2103-AY2324S1/forum#225]
I am using M1 Mac, I have followed the Mac advisory as well and my project structure is azul java 11.

This is the error i encounter when running the main file
<img width="1396" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/0c7ec3d9-3091-4520-8ca5-ebb28fee1e42">

This is the output of java -version 
<img width="560" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/cada800c-5d6a-4ff2-a5b5-26dbbed1f061">

My project structure
<img width="1027" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/531b8aac-bb67-4504-8c7d-16012ae2944b">

Had a look at the mac advisory as well and think i have followed it appropriately.

This is the version of java i downloaded 

<img width="1165" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/c837028d-e06e-4812-af99-54ce3a2f2d4d">

**Comment by damithc** [comment]
@Nid21cs What happens if you run AB3 from the terminal? i.e., `./gradlew run`

**Comment by Nid21cs** [comment]
> .\gradlew run

this is the error i get when i run ./gradlew run

```
Sep 28, 2023 4:26:43 PM seedu.address.Main main
WARNING: The warning about Unsupported JavaFX configuration below can be ignored.
Sep 28, 2023 4:26:43 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @75a1bdd8'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nidhish/.openjfx/cache/17.0.7/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/nidhish/.openjfx/cache/17.0.7/libprism_es2.dylib
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1850)
        at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
        at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.base/java.lang.Thread.run(Thread.java:829)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nidhish/.openjfx/cache/17.0.7/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/nidhish/.openjfx/cache/17.0.7/libprism_sw.dylib
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1850)
        at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
        at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:43)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:42)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.base/java.lang.Thread.run(Thread.java:829)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:829)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Users/nidhish/Library/Java/JavaVirtualMachines/azul-11.0.20.1/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 612ms
3 actionable tasks: 1 executed, 2 up-to-date
```

**Comment by damithc** [comment]
@Nid21cs Are you able to run the original AB3 jar file? https://github.com/se-edu/addressbook-level3/releases

**Comment by Nid21cs** [comment]
> @Nid21cs Are you able to run the original AB3 jar file? https://github.com/se-edu/addressbook-level3/releases

No prof i cant i run into a similar error as well 

```
Sep 28, 2023 5:42:57 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @72156761'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nidhish/.openjfx/cache/17.0.7/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/nidhish/.openjfx/cache/17.0.7/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1850)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:829)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nidhish/.openjfx/cache/17.0.7/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/nidhish/.openjfx/cache/17.0.7/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1850)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:43)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:829)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I

**Comment by damithc** [comment]
@Nid21cs hmm.... that is a serious issue. I'm not a Mac user myself; so we need to get help from other Mac users.
This part in your earlier screenshot suggests there are other JDKs in your system.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/3d51db3b-3634-41d3-9e71-45ba06d2e9cb)

Any chance you can remove all Java versions and install only the version we have suggested, perhaps using SDKman tool as suggested in https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html#programming-language ?

**Comment by damithc** [comment]
@ryanozx this forum thread is about the tP (in which the build.gradle file comes with the repo).

**Comment by woojiahao** [comment]
It might also be a misconfigured JDK filepath. Perhaps you downloaded JDK into your ~/Downloads folder and Intellij is pointing to that by accident? You might want to check your Downloads folder for such a folder and remove it so Intellij will point to your system JDK

**Comment by ryanozx** [comment]
> @ryanozx this forum thread is about the tP (in which the build.gradle file comes with the repo).

Sorry Prof, would you like me to remove my comment in that case?

**Comment by Nid21cs** [comment]
> It might also be a misconfigured JDK filepath. Perhaps you downloaded JDK into your ~/Downloads folder and Intellij is pointing to that by accident? You might want to check your Downloads folder for such a folder and remove it so Intellij will point to your system JDK

I have checked my downloads folder and removed any jdk that is not zulu 11 jdk. This changed the error in that the error now comes from the appropriate path i believe?

<img width="1442" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/8de4a760-b055-4c96-9e7f-c7d127426746">

Running `whereis java` outputs `/usr/bin/java` as well.

I have also set my JAVA_HOME/JDK_HOME system variables to point to /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home

Running the command `echo $JAVA_HOME` outputs `/Users/nidhish/Library/Java/JavaVirtualMachines/azul-11.0.20.1/Contents/Home`

Should the `echo $JAVA_HOME` be returning azul-11.0.20.1 instead of zulu-11.jdk?

<img width="492" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/753831f6-de8c-40ce-9b53-cbd96ae853f0">

**Comment by woojiahao** [comment]
Awesome, did you try re-running the Gradle task and is the error still persisting?

**Comment by Nid21cs** [comment]
> Awesome, did you try re-running the Gradle task and is the error still persisting?

Yes i ran `./gradlew run` and i encounter the same error. 

I restarted my IDE and terminal as well as deleted the .idea folder

**Comment by damithc** [comment]
Other Mac M1 users here who can confirm the presence (or the absence) of this problem on your computer? For example, are you able to run the [original AB3 jar file](https://github.com/se-edu/addressbook-level3/releases) on your M1 Mac?

**Comment by yanghengtang** [comment]
M1 Mac user here. I get the same error as I attempt to run the AB3 jar file with `java -jar addressbook.jar`.

The error message:
```
Sep 29, 2023 12:39:00 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6996f246'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/yanghengtang/.openjfx/cache/17.0.7/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/yanghengtang/.openjfx/cache/17.0.7/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2622)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1848)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:834)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/yanghengtang/.openjfx/cache/17.0.7/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/yanghengtang/.openjfx/cache/17.0.7/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2622)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1848)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:43)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:834)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by damithc** [comment]
@yanghengtang @Nid21cs How about this one (unzip first)? [addressbook.zip](https://github.com/nus-cs2103-AY2324S1/forum/files/12752143/addressbook.zip)

**Comment by Nid21cs** [comment]
> addressbook.zip

Hi prof, This works. I went back and checked the previous addressbook and that still does not run

**Comment by yanghengtang** [comment]
This works for me as well

**Comment by dom-buri** [comment]
M1 Mac user here. I got the same error but managed to fix it by editing the build.gradle file. This is the changes I made. https://github.com/AY2324S1-CS2103-F13-3/tp/pull/8/files

**Comment by damithc** [comment]
> M1 Mac user here. I got the same error but managed to fix it by editing the build.gradle file. This is the changes I made. https://github.com/AY2324S1-CS2103-F13-3/tp/pull/8/files

Thanks @dom-buri 
@yanghengtang @Nid21cs that's the same change I did to generate the new JAR file. So, you can do the same.

**Comment by EmilyOng** [comment]
Hi! I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). 

I can confirm that the following zip file uploaded by prof works, on Mac Intel.

> How about this one (unzip first)? [addressbook.zip](https://github.com/nus-cs2103-AY2324S1/forum/files/12752143/addressbook.zip)

**Comment by yanghengtang** [comment]
Thanks prof @damithc and @dom-buri. Able to get it to work now.

**Comment by Nid21cs** [comment]
> https://github.com/AY2324S1-CS2103-F13-3/tp/pull/8/files

This works thank you very much I will close this issue for now.

**Comment by Nid21cs** [comment]
I realise the build.gradle file cannot be edited as non mac aarch users will then encounter the same issue, so the gradle file in the team repo cant be changed and cant include both as well as i will encounter the same error again. Any ideas? 

When other groups do testing any m1 mac users wont be able to run our application without changing the gradle file as well.

**Comment by Nid21cs** [comment]
> M1 Mac user here. I got the same error but managed to fix it by editing the build.gradle file. This is the changes I made. https://github.com/AY2324S1-CS2103-F13-3/tp/pull/8/files

@dom-buri Out of curiosity when u merge to ur main repo are youre non m1 mac users still able to run the application?

**Comment by damithc** [comment]
> I realise the build.gradle file cannot be edited as non mac aarch users will then encounter the same issue

Perhaps Intel Mac users can confirm if they can run [addressbook.zip](https://github.com/nus-cs2103-AY2324S1/forum/files/12752143/addressbook.zip) ?
It should not affect Windows and Linux users.

**Comment by dom-buri** [comment]
> @dom-buri Out of curiosity when u merge to ur main repo are youre non m1 mac users still able to run the application?

My team mate who is a Windows user is able to run the application but I'm not sure about Intel Mac users.

**Comment by Nid21cs** [comment]
> > I realise the build.gradle file cannot be edited as non mac aarch users will then encounter the same issue
> 
> Perhaps Intel Mac users can confirm if they can run [addressbook.zip](https://github.com/nus-cs2103-AY2324S1/forum/files/12752143/addressbook.zip) ? It should not affect Windows and Linux users.

yes prof my group member is an intel user and if the gradle build is changed she encounters the same error as i did.
having both configurations does not solve the issue as well.

**Comment by damithc** [comment]
@Nid21cs Can you ask your Intel-Mac friend to confirm she is using Zulu JDK and still cannot run [addressbook.zip](https://github.com/nus-cs2103-AY2324S1/forum/files/12752143/addressbook.zip)? Because another Intel-Mac user (in a different thread) confirmed she can run [addressbook.zip](https://github.com/nus-cs2103-AY2324S1/forum/files/12752143/addressbook.zip)
Perhaps the exact Zulu JDK version matters as well.

>Works for me too.
>
>OS: Mac Intel (version 10.15.7)
>
>Running java --version
>```
>openjdk version "11.0.16" 2022-07-19 LTS
>OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
>OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
>```

**Comment by Nid21cs** [comment]
> @Nid21cs Can you ask your Intel-Mac friend to confirm she is using Zulu JDK and still cannot run [addressbook.zip](https://github.com/nus-cs2103-AY2324S1/forum/files/12752143/addressbook.zip)? Because another Intel-Mac user (in a different thread) confirmed she can run [addressbook.zip](https://github.com/nus-cs2103-AY2324S1/forum/files/12752143/addressbook.zip) Perhaps the exact Zulu JDK version matters as well.
> 
> > Works for me too.
> > OS: Mac Intel (version 10.15.7)
> > Running java --version
> > ```
> > openjdk version "11.0.16" 2022-07-19 LTS
> > OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
> > OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
> > ```

She can run the addressbook.zip... Not sure why one works but one doesn't

Her `java -version`:

<img width="1061" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122248240/809c4d49-e819-42df-ac3b-d22a510fb8e7">

**Comment by damithc** [comment]
> She can run the addressbook.zip... Not sure why one works but one doesn't

@Nid21cs You can update the build.gradle as suggested, and do a `./gradlew clean shadowjar` to create a clean jar file, and get it tested by your friend (in case the previous jar file you gave is not updated).

**Comment by damithc** [comment]
@Nid21cs Our TA Danny is using Mac M1, and the following JDK (same as yours?), and he can run both original and new AB-3 JAR files 🤔 

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/137ae3c1-1fd8-4c74-ab75-e2823be109a2)

As an extreme measure, I suggest you try this:
Remove all java versions. Confirm `java -jar` command fails (as there are no Java in your comp). Then, install the recommended JDK version and try again.

**Comment by damithc** [comment]
@Nid21cs Any updates? Based on data received so far, it looks like the tP should work on Mac computers (both Intel and ARM variants) that use the prescribed  JDK, even without any changes to build.gradle. However, a few who hasve multiple JDK versions installed seem to run into the problem that you encountered.

**Comment by Nid21cs** [comment]
> @Nid21cs Our TA Danny is using Mac M1, and the following JDK (same as yours?), and he can run both original and new AB-3 JAR files 🤔
> 
> ![image](https://user-images.githubusercontent.com/1673303/271526502-137ae3c1-1fd8-4c74-ab75-e2823be109a2.png)
> 
> As an extreme measure, I suggest you try this: Remove all java versions. Confirm `java -jar` command fails (as there are no Java in your comp). Then, install the recommended JDK version and try again.

Hi prof, Sorry for the late reply I managed to fix it big thank you to everyone who helped out. 

Removing all java versions worked, and for anyone who still has this issue, the below command will help locate all java versions!

```
/usr/libexec/java_home -V
```

**Comment by damithc** [comment]
> Hi prof, Sorry for the late reply I have done this i believe? I used the method given in the [link](https://www.youtube.com/watch?v=wwV_L3lKYYw&ab_channel=ProgrammingKnowledge2) as well as checking through my downloads folder manually, and deleted what i believe is any jdk versions as well however when i run java -version i still see the same output. I also ran the following commands in an attempt to remove any java versions

@Nid21cs So, this may be a case of 'hidden Java version' problem. Perhaps you can open a new thread asking how to remove Java entirely from a Mac so that it gets more focused inputs.

**Comment by Nid21cs** [comment]
> > Hi prof, Sorry for the late reply I have done this i believe? I used the method given in the [link](https://www.youtube.com/watch?v=wwV_L3lKYYw&ab_channel=ProgrammingKnowledge2) as well as checking through my downloads folder manually, and deleted what i believe is any jdk versions as well however when i run java -version i still see the same output. I also ran the following commands in an attempt to remove any java versions
> 
> @Nid21cs So, this may be a case of 'hidden Java version' problem. Perhaps you can open a new thread asking how to remove Java entirely from a Mac so that it gets more focused inputs.

Thank you prof i managed to fix it i have edited my earlier comment as well with how i solved it and will now close the issue
