### ISSUE TITLE
VSCode Testing issue

### ISSUE THREAD

**Issue by MagnificentCreature** [nus-cs2103-AY2324S1/forum#235]
I am using VSCode and forked AB3, but I cannot run the tests using JUnit the old way. 
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/61371541/860d80a4-c044-4d6b-ab5e-a7e54473d8ce)
The green test button is there, but I click it and then nothing noteworthy happens, you can even see on the top left hand side it says no test results yet.
Thankfully gradle tests still function and has feedbacked that some of these tests do not pass, but it becomes hard to debug when I cannot press the green button and see it running.

Has anyone else encountered a similar issue on VSCode?

**Comment by MagnificentCreature** [comment]
Update: Problem not solved, but I found this in the debug console
```
java.lang.NoClassDefFoundError: org/junit/platform/engine/EngineDiscoveryListener
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
ClassLoader.java:1016
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
SecureClassLoader.java:174
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
BuiltinClassLoader.java:800
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
BuiltinClassLoader.java:698
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
BuiltinClassLoader.java:621
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
BuiltinClassLoader.java:579
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
ClassLoaders.java:178
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
ClassLoader.java:521
	at org.junit.platform.launcher.core.ListenerRegistry.forLauncherDiscoveryListeners(ListenerRegistry.java:37)
	at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:40)
	at org.junit.platform.launcher.core.LauncherFactory.createDefaultLauncher(LauncherFactory.java:134)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:125)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:109)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
NativeConstructorAccessorImpl.java:62
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
DelegatingConstructorAccessorImpl.java:45
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
Constructor.java:490
	at java.base/java.lang.Class.newInstance(Class.java:584)
Class.java:584
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:371)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:366)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:310)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:225)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.engine.EngineDiscoveryListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
BuiltinClassLoader.java:581
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
ClassLoaders.java:178
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
ClassLoader.java:521
	... 25 more
	```

**Comment by MagnificentCreature** [comment]
Problem solved:
Adding this line to build.gradle dependencies did it
```
testImplementation 'org.junit.platform:junit-platform-launcher:1.4.0'
```

I placed it in this section

```
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: jUnitVersion
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: jUnitVersion
    testImplementation 'org.junit.platform:junit-platform-launcher:1.4.0'
```

**Comment by damithc** [comment]
Thanks for sharing this solution @MagnificentCreature 
Although VSCode is not our supported IDE (probably that's why you didn't get any inputs from others), this might help anyone who is using VSCode. 
It is also interesting why Intellij users didn't report a similar problem. Let's hope this update to the gradle file doesn't affect your team members who might be using Intellij. On a related note, in a team project, things can be smoother if all team members are using the same IDE, e.g., you can share IDE settings files via the repo.
