### ISSUE TITLE
Error "com/google/common/util/concurrent/internal/InternalFutureFailureAccess"

### ISSUE THREAD

**Issue by adammangzijun** [nus-cs2103-AY2324S1/forum#260]
Any idea why I couldn't run/build/clean my app. It says Exception:"java.lang.NoClassDefFoundError". However, my peers didn't have this error using the same code.Need a little help here.

**Comment by damithc** [comment]
@adammangzijun Perhaps you can also share the full error message here? copy-paste the text rather than a screenshot.

**Comment by damithc** [comment]
Also,
* Which OS are you on?
* When do you encounter the error? e.g., running which gradle task in which terminal?
* Are you able to run the [original AB3 jar](https://github.com/se-edu/addressbook-level3/releases/tag/v0.2.2ea)?

**Comment by adammangzijun** [comment]
This is the entire error message:
````
com/google/common/util/concurrent/internal/InternalFutureFailureAccess
> com.google.common.util.concurrent.internal.InternalFutureFailureAccess

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/internal/InternalFutureFailureAccess
	at com.google.common.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3472)
	at com.google.common.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3476)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2134)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4859)
	at org.gradle.internal.resources.AbstractResourceLockRegistry.getOrRegisterResourceLock(AbstractResourceLockRegistry.java:44)
	at org.gradle.internal.work.DefaultWorkerLeaseService$WorkerLeaseLockRegistry.getResourceLock(DefaultWorkerLeaseService.java:391)
	at org.gradle.internal.work.DefaultWorkerLeaseService.getWorkerLease(DefaultWorkerLeaseService.java:99)
	at org.gradle.internal.work.DefaultWorkerLeaseService.getWorkerLease(DefaultWorkerLeaseService.java:104)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:119)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:103)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
	at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:100)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:88)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:63)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:58)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.internal.InternalFutureFailureAccess
	... 52 more
````

**Comment by adammangzijun** [comment]
1. I'm currently using Windows 11.
2.The error occurs when I try to build gradle or run main in intelliJ terminal.
3.I am able to run the original AB3 jar

**Comment by damithc** [comment]
@adammangzijun 

You may want to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

While waiting for inputs from others, here are some things you can try these 'common remedies' one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

If the above doesn't work, you can also share the following info.
* When did this start happening? 
* Are you running the master branch of your team repo? If so, give the link to your team repo.
* If it is happening on a different branch or after you modified some code, push the code to your fork and give the link to branch/PR here.

**Comment by adammangzijun** [comment]
Sorry but the above solutions doesn't work either, it started to happen when I started to work on our edit feature.
Even cloning the master branch of team repo and running it give the same error.
The given link is the our team repo link: https://github.com/AY2324S1-CS2103T-T12-4/tp.git

**Comment by damithc** [comment]
@adammangzijun On a related note, your team repo master branch is failing CI. Merging CI-failing PRs means you lose one of the important benefits of the CI -- i.e., the ability to tell if the base code is correct. For example, because CI is failing due to a different error, we can't use CI to check if your error happens on the CI as well. It might help if your team fix the CI error of the current master branch and everyone sync with that first.

> The given link is the our team repo link: https://github.com/AY2324S1-CS2103T-T12-4/tp.git

This is something others can help verify.

**Comment by SPWwj** [comment]
> Sorry but the above solutions doesn't work either, it started to happen when I started to work on our edit feature. Even cloning the master branch of team repo and running it give the same error. The given link is the our team repo link: https://github.com/AY2324S1-CS2103T-T12-4/tp.git

Hi @AdamMangZiJun I'm a senior from the previous batch.
You may consider adding the following dependencies to your project:

```
dependencies {
    // Add Google Guava library
    implementation 'com.google.guava:guava:30.1-jre' 
}

```

Additionally, it appears that some tests have failed. You may want to address these issues before proceeding further.

<img width="1413" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/30100720/5e97c358-f4e3-4440-b679-b64249f4ce21">

**Comment by cheeheng** [comment]
Hi, I am a student from a previous batch. I have searched online for the problem. The problem is related to the Google Guava library. Here are some possible fixes you can take:

1. Add the code block below to build.gradle (or merge the implementation lines under dependencies block if the dependencies block already exists), similar suggestion to @SPWwj, but instead using the latest version according to the [Google Guava library GitHub repository](https://github.com/google/guava), as of 16 October 2023. This library has a dependendency listed on its [documentation](https://github.com/google/guava/wiki/UseGuavaInYourBuild#what-about-guavas-own-dependencies), whch is com.google.guava:failureaccess:1.0.1. The missing dependency could be causing the error.

```
dependencies {
    implementation("com.google.guava:guava:32.1.3-jre")
    implementation("com.google.guava:failureaccess:1.0.1")
}
```

2. I have seen cases on StackOverflow where some version mismatch caused the error, such as [this](https://stackoverflow.com/questions/64608914/java-lang-noclassdeffounderror-com-google-common-util-concurrent-internal-inter). If you have multiple versions of Java installed, then you may have to delete all the unnecessary versions.

**Comment by adammangzijun** [comment]
Hey thanks a lot for the help. I've fixed the issue by re-cloning my repo. I think there might an issue with my gradle files, i deleted my .gradle files and re-build everything and now it is working.
