### ISSUE TITLE
Run time error when following javaFX tutorial part 1

### ISSUE THREAD

**Issue by DistractedCat** [nus-cs2103-AY2324S1/forum#90]
When I try to run the main method in Launcher, it shows this error:

```
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class com.mimi.main.Mimi
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:891)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodException: com.mimi.main.Mimi.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:802)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2d349747'

	at java.base/java.security.AccessController.doPrivileged(Native Method)
Caused by: java.lang.NoSuchMethodException: com.mimi.main.Mimi.<init>()

	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	... 1 more

Execution failed for task ':Launcher.main()'.
> Process 'command 'C:/Program Files/Java/jdk-11/bin/java.exe'' finished with non-zero exit value 1
```

I have already followed the instructions and added the necessary dependencies in my build.gradle file.  Anyone else encounrtered this issue?

**Comment by DistractedCat** [comment]
It seems as though it was a constructor issue, fixed!
